version: '3.4'

services:
  dockervue3:
    image: dockervue3
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
